### ISSUE TITLE
Plugin broken

### ISSUE THREAD

**Issue by Eraidu** [jdugge/BufferByPercentage#10]
Hi, 
I am fairly new to QGIS, and I was unable to determine if this issue has already been dealt with. The plugin does not appear to be working with QGIS 2.16. I can see no one has been active on here for some time, so I will post further details if someone replies.

Regards

**Comment by jdugge** [comment]
Thanks for the bug report. It seems that the fTools plugin, which Buffer by Percentage uses, has been incorporated into the main code base. I'll fix the error next week.

**Comment by Eraidu** [comment]
Thanks for that,much appreciated!

Date: Wed, 27 Jul 2016 09:37:04 -0700

**Comment by jdugge** [comment]
@Eraidu: I uploaded a new version to the QGIS plugin repository. Could you give it a try and briefly let me know whether the issue is fixed for you?

**Comment by Eraidu** [comment]
Yep, it is working fine now.Thanks a bunch.

Date: Tue, 2 Aug 2016 15:12:59 -0700

**Comment by jdugge** [comment]
@Eraidu: Excellent! Thanks again for reporting the issue.
