### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by culland** [jdugge/BufferByPercentage#13]
Keep getting the following error when I try to buffer my polygons by 35% and save to new shape file.  My polygons are only 0.2 meters wide, wonder if that is the issue?

Error message:

Traceback (most recent call last):
  File "C:/Users/Bob/.qgis2/python/plugins\BufferByPercentage\bufferbypercentage.py", line 181, in run
    self.target_factor, self.segments)
  File "C:/Users/Bob/.qgis2/python/plugins\BufferByPercentage\bufferbypercentage.py", line 55, in find_buffer_length
    area_unscaled, target_factor)
  File "C:/Users/Bob/.qgis2/python/plugins\BufferByPercentage\bufferbypercentage.py", line 80, in secant
    dx = f * (x - oldx) / float(f - oldf)
ZeroDivisionError: float division by zero

**Comment by jdugge** [comment]
Thanks for the report, I'll look into it.

Would you mind checking if you get the same error if you buffer with 150 %?
And could you attach a small sample shapefile that includes a feature that causes the error to appear?

**Comment by culland** [comment]
Same error with 150%. Attached a small sample. Thanks!

[test.zip](https://github.com/jdugge/BufferByPercentage/files/592766/test.zip)

**Comment by jdugge** [comment]
Thanks, that's indeed a pretty challenging dataset. I'll fix the code to deal with this properly.

Interestingly, I don't get a `float division by zero` error (but the resulting geometry is still wrong). What version of QGIS and BufferByPercentage are you using?

**Comment by culland** [comment]
2.16.0-Nødebo and 0.2.4.2 version of the plugin

**Comment by jdugge** [comment]
Sorry, I was using an older version of the plugin before: I can reproduce the behaviour using the same versions as you.

I'll let you know when this is fixed.

**Comment by culland** [comment]
great, many thanks

**Comment by jdugge** [comment]
I've uploaded a new version (0.2.5) of the plugin to the repository. Would you be so kind to check whether this fixes the problem for you?
