### ISSUE TITLE
Long time for buffering percentages over 100 on irregular polygons

### ISSUE THREAD

**Issue by newcomb-d** [jdugge/BufferByPercentage#15]
Perhaps trying to exceed the intent of the program with this observation.  We have a groups of trees ( 1 or more trees)  for which convex hulls are created. We create a buffer of 200 feet ( 60.96m) , but there is also a minimum area requirement of 10 acres ( 40468.6 sq m) per buffered area. 
Used this equation to generate the percentage that a polygon must expand in order to meet the area requirement in the field calculator.

if(((40468.6 - $area) <0),100,((((40468.6-$area)/$area)*100)+100))
Bufferbypercentage works fine if the original buffer is from a single tree. However,when the convex hull of a group of multiple trees is less than 10 acres and needs to be buffered out to 10 acres the seems to get stuck and gives ever increasing estimates on the completion time 

 While there are methods of incrementally buffering out until the threshold area is reached see ( https://github.com/vpdawson/Habitat-Manager ( working with the author ,had pointed him to your project)) I was wondering if this was a bug, or just beyond the intent of the program?

**Comment by jdugge** [comment]
That's a use case that should definitely be possible with this plugin, so this sounds like a bug to me. 

Are you able to share the convex hull dataset, or a subset of the dataset that I can use to reproduce the problem?

**Comment by newcomb-d** [comment]
[fake_testing_data.zip](https://github.com/jdugge/BufferByPercentage/files/4738103/fake_testing_data.zip)
Here are some test polygons that exhibit the same behavior.  I was originally working in shapefile format, but the issue shows up quicker in geopackage format ( at 8% completion rather than 18%)

**Comment by jdugge** [comment]
The issue should be fixed now.

Would you mind testing the updated plugin ([BufferByPercentage-0.3.3.zip](https://github.com/jdugge/BufferByPercentage/files/4739887/BufferByPercentage-0.3.3.zip)) before I upload it to the QGIS Plugin Repository?

**Comment by newcomb-d** [comment]
I will get to it today!
________________________________

**Comment by newcomb-d** [comment]
That did the trick! It works fine now.  Thanks!

**Comment by jdugge** [comment]
Fantastic!

The new version of the plugin is available in the QGIS Plugin Repository now.
